version: '3'

services:
  db:
    image: mysql:5.7

    command: --innodb-use-native-aio=0

    container_name: db

    restart: always

    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=fullcycle

    volumes:
      - ./mysql:/var/lib/mysql

    networks:
      - fullcycle-node

  app:
    build: .

    container_name: app

    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh

    volumes:
      - ./app:/usr/app

    networks:
      - fullcycle-node

    depends_on:
      - db

  nginx: 
    build: 
      context: ./nginx

    container_name: nginx

    ports: 
      - 8080:80

    networks:
      - fullcycle-node

    depends_on:
      - app
    
networks:
  fullcycle-node:
    driver: bridge
  
      