version: '3'

services:
  db:
    image: mysql:5.7

    command: --innodb-use-native-aio=0

    container_name: db

    restart: always

    tty: true

    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=fullcycle

    volumes:
      - ./mysql:/var/lib/mysql

    networks:
      - fullcycle-node

  app:
    build:
        context: .

    container_name: app

    command: "npm start"

    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh

    tty: true

    # volumes:
    #   - ./app:/usr/app
    #   - /usr/app/node_modules

    networks:
      - fullcycle-node

    depends_on:
     - db

  nginx: 
    build: 
      context: ./nginx

    container_name: nginx

    tty: true

    ports: 
      - 8080:80

    networks:
      - fullcycle-node

    depends_on:
      - app
    
networks:
  fullcycle-node:
    driver: bridge
  
      